<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            ['name' => 'Chibombo District', 'province_id' => 4],
            ['name' => 'Chisamba District', 'province_id' => 4],
            ['name' => 'Chitambo District', 'province_id' => 4],
            ['name' => 'Kabwe District', 'province_id' => 4],
            ['name' => 'Kapiri Mposhi District', 'province_id' => 4],
            ['name' => 'Luano District', 'province_id' => 4],
            ['name' => 'Mkushi District', 'province_id' => 4],
            ['name' => 'Mumbwa District', 'province_id' => 4],
            ['name' => 'Ngabwe District', 'province_id' => 4],
            ['name' => 'Serenje District', 'province_id' => 4],
            ['name' => 'Shibuyunji District', 'province_id' => 4],
            ['name' => 'Chililabombwe District', 'province_id' => 2],
            ['name' => 'Chingola District', 'province_id' => 2],
            ['name' => 'Kalulushi District', 'province_id' => 2],
            ['name' => 'Kitwe District', 'province_id' => 2],
            ['name' => 'Luanshya District', 'province_id' => 2],
            ['name' => 'Lufwanyama District', 'province_id' => 2],
            ['name' => 'Masaiti District', 'province_id' => 2],
            ['name' => 'Mpongwe District', 'province_id' => 2],
            ['name' => 'Mufulira District', 'province_id' => 2],
            ['name' => 'Ndola District', 'province_id' => 2],
            ['name' => 'Chadiza District', 'province_id' => 3],
            ['name' => 'Chama District', 'province_id' => 3],
            ['name' => 'Chasefu District', 'province_id' => 3],
            ['name' => 'Chipangali District', 'province_id' => 3],
            ['name' => 'Chipata District', 'province_id' => 3],
            ['name' => 'Kasenengwa District', 'province_id' => 3],
            ['name' => 'Katete District', 'province_id' => 3],
            ['name' => 'Lumezi District', 'province_id' => 3],
            ['name' => 'Lundazi District', 'province_id' => 3],
            ['name' => 'Lusangazi District', 'province_id' => 3],
            ['name' => 'Mambwe District', 'province_id' => 3],
            ['name' => 'Nyimba District', 'province_id' => 3],
            ['name' => 'Petauke District', 'province_id' => 3],
            ['name' => 'Sinda District', 'province_id' => 3],
            ['name' => 'Vubwi District', 'province_id' => 3],
            ['name' => 'Chembe District', 'province_id' => 10],
            ['name' => 'Chiengi District', 'province_id' => 10],
            ['name' => 'Chifunabuli District', 'province_id' => 10],
            ['name' => 'Chipili District', 'province_id' => 10],
            ['name' => 'Kawambwa District', 'province_id' => 10],
            ['name' => 'Lunga District', 'province_id' => 10],
            ['name' => 'Mansa District', 'province_id' => 10],
            ['name' => 'Milenge District', 'province_id' => 10],
            ['name' => 'Mwansabombwe District', 'province_id' => 10],
            ['name' => 'Mwense District', 'province_id' => 10],
            ['name' => 'Nchelenge District', 'province_id' => 10],
            ['name' => 'Samfya District', 'province_id' => 10],
            ['name' => 'Chilanga District', 'province_id' => 1],
            ['name' => 'Chongwe District', 'province_id' => 1],
            ['name' => 'Kafue District', 'province_id' => 1],
            ['name' => 'Luangwa District', 'province_id' => 1],
            ['name' => 'Lusaka District', 'province_id' => 1],
            ['name' => 'Rufunsa District', 'province_id' => 1],
            ['name' => 'Chinsali District', 'province_id' => 5],
            ['name' => 'Isoka District', 'province_id' => 5],
            ['name' => 'Kanchibiya District', 'province_id' => 5],
            ['name' => 'Lavushimanda District', 'province_id' => 5],
            ['name' => 'Mafinga District', 'province_id' => 5],
            ['name' => 'Mpika District', 'province_id' => 5],
            ['name' => 'Nakonde District', 'province_id' => 5],
            ['name' => 'Shiwang\'andu District', 'province_id' => 5],
            ['name' => 'Chilubi District', 'province_id' => 6],
            ['name' => 'Kaputa District', 'province_id' => 6],
            ['name' => 'Kasama District', 'province_id' => 6],
            ['name' => 'Lunte District', 'province_id' => 6],
            ['name' => 'Lupososhi District', 'province_id' => 6],
            ['name' => 'Luwingu District', 'province_id' => 6],
            ['name' => 'Mbala District', 'province_id' => 6],
            ['name' => 'Mporokoso District', 'province_id' => 6],
            ['name' => 'Mpulungu District', 'province_id' => 6],
            ['name' => 'Mungwi District', 'province_id' => 6],
            ['name' => 'Nsama District', 'province_id' => 6],
            ['name' => 'Senga District', 'province_id' => 6],
            ['name' => 'Chavuma District', 'province_id' => 7],
            ['name' => 'Ikelenge District', 'province_id' => 7],
            ['name' => 'Kabompo District', 'province_id' => 7],
            ['name' => 'Kasempa District', 'province_id' => 7],
            ['name' => 'Kalumbila District', 'province_id' => 7],
            ['name' => 'Manyinga District', 'province_id' => 7],
            ['name' => 'Mufumbwe District', 'province_id' => 7],
            ['name' => 'Mushindamo District', 'province_id' => 7],
            ['name' => 'Mwinilunga District', 'province_id' => 7],
            ['name' => 'Solwezi District', 'province_id' => 7],
            ['name' => 'Zambezi District', 'province_id' => 7],
            ['name' => 'Chikankata District', 'province_id' => 9],
            ['name' => 'Chirundu District', 'province_id' => 9],
            ['name' => 'Choma District', 'province_id' => 9],
            ['name' => 'Gwembe District', 'province_id' => 9],
            ['name' => 'Itezhi-Tezhi District', 'province_id' => 9],
            ['name' => 'Kalomo District', 'province_id' => 9],
            ['name' => 'Kazungula District', 'province_id' => 9],
            ['name' => 'Livingstone District', 'province_id' => 9],
            ['name' => 'Mazabuka District', 'province_id' => 9],
            ['name' => 'Monze District', 'province_id' => 9],
            ['name' => 'Namwala District', 'province_id' => 9],
            ['name' => 'Pemba District', 'province_id' => 9],
            ['name' => 'Siavonga District', 'province_id' => 9],
            ['name' => 'Sinazongwe District', 'province_id' => 9],
            ['name' => 'Zimba District', 'province_id' => 9],
            ['name' => 'Kalabo District', 'province_id' => 8],
            ['name' => 'Kaoma District', 'province_id' => 8],
            ['name' => 'Limulunga District', 'province_id' => 8],
            ['name' => 'Luampa District', 'province_id' => 8],
            ['name' => 'Lukulu District', 'province_id' => 8],
            ['name' => 'Mitete District', 'province_id' => 8],
            ['name' => 'Mongu District', 'province_id' => 8],
            ['name' => 'Mulobezi District', 'province_id' => 8],
            ['name' => 'Mwandi District', 'province_id' => 8],
            ['name' => 'Nalolo District', 'province_id' => 8],
            ['name' => 'Nkeyema District', 'province_id' => 8],
            ['name' => 'Senanga District', 'province_id' => 8],
            ['name' => 'Sesheke District', 'province_id' => 8],
            ['name' => 'Shang\'ombo District', 'province_id' => 8],
            ['name' => 'Sikongo District', 'province_id' => 8],
            ['name' => 'Sioma District', 'province_id' => 8],
        ];

        DB::table('districts')->insert($districts);
    }
}
