<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Add is_setup_debt flag to distinguish debts created during initial
     * system setup vs. those auto-generated by the monthly shortfall process.
     */
    public function up(): void
    {
        Schema::table('office_debts', function (Blueprint $table) {
            $table->enum('is_setup_debt', ['true', 'false'])
                  ->default('false')
                  ->after('debt_year');
        });
    }

    public function down(): void
    {
        Schema::table('office_debts', function (Blueprint $table) {
            $table->dropColumn('is_setup_debt');
        });
    }
};
